from typing import Any, Protocol

from studio.domain.jobs import ClaimedJob


class JobQueue(Protocol):
    def claim(self) -> ClaimedJob | None: ...
    def checkpoint(self, job: ClaimedJob, stage: str | None = None) -> None: ...
    def complete(self, job: ClaimedJob, result: dict[str, Any]) -> None: ...
    def fail(self, job: ClaimedJob, code: str, message: str) -> None: ...
